version: '3.4'

services:

  webmvc:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=EpiLef505050
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"