/**
 * Test
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Game } from './game';
import { User } from './user';

export interface UserGame { 
    id: number;
    idGame: number;
    idUser: number;
    users?: Array<User>;
    games?: Array<Game>;
}